-- =========================================================
-- Customer Behavior Analysis - SQL Queries (PostgreSQL)
-- =========================================================

-- Q1. Total revenue generated by gender
SELECT 
    gender, 
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;


-- Q2. Customers who used a discount and spent above average
SELECT 
    customer_id, 
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
        SELECT AVG(purchase_amount) 
        FROM customer
  )
ORDER BY purchase_amount DESC;


-- Q3. Top 5 products with highest average review rating
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating::NUMERIC), 2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;


-- Q4. Average purchase amount by shipping type
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;


-- Q5. Spending behavior: Subscribers vs Non-Subscribers
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q6. Top 5 products with highest discount usage rate
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*), 
    2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Customer segmentation based on purchase history
WITH customer_segments AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM customer_segments
GROUP BY customer_segment
ORDER BY customer_count DESC;


-- Q8. Top 3 most purchased products per category
WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_orders,
    rank
FROM ranked_products
WHERE rank <= 3
ORDER BY category, rank;


-- Q9. Subscription behavior of repeat buyers (>5 purchases)
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyer_count DESC;


-- Q10. Revenue contribution by age group
SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
